version: '3'
services:
  ghost:
    build:
      context: .
    environment:
      url: http://localhost:2368/
    volumes:
      - ./ghost:/var/lib/ghost/content

      # Without this line, ghost would descend into theme dependencies and cause problems
      - empty:/var/lib/ghost/content/themes/casper-maat/node_modules
    ports:
      - "2368:2368"

volumes:
  empty:
