{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ghost.fullname" . }}
  {{- if .Values.serviceAccount.annotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.serviceAccount.annotations "context" $ ) | nindent 4 }}
  {{- end }}
{{- end -}}
