{{- if .Values.adminService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ghost.fullname" . }}-admin
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  {{- if .Values.adminService.annotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.adminService.annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.adminService.type }}
  {{- if (or (eq .Values.adminService.type "LoadBalancer") (eq .Values.adminService.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.adminService.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if eq .Values.adminService.type "LoadBalancer" }}
  loadBalancerIP: {{ default "" .Values.adminService.loadBalancerIP | quote }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.adminService.port }}
      targetPort: http
      {{- if (and (or (eq .Values.adminService.type "NodePort") (eq .Values.adminService.type "LoadBalancer")) (not (empty .Values.adminService.nodePorts.http))) }}
      nodePort: {{ .Values.adminService.nodePorts.http }}
      {{- else if eq .Values.adminService.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {{- if .Values.adminService.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.adminService.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  selector: {{ include "common.labels.matchLabels" . | nindent 4 }}
{{- end }}
